const STARTUP_JOBS_ID_PREFIX = 'Actor/Startupjobs - ';
const ERROR_TYPES = {
  CREATE_APPLICANT: 'CREATE_APPLICANT',
  CREATE_NOTE: 'CREATE_NOTE',
};

module.exports = {
  STARTUP_JOBS_ID_PREFIX,
  ERROR_TYPES,
};
