const STARTUP_JOBS_ID_PREFIX = 'Actor/Startupjobs - ';

const JAZZ_HR_POST_ERROR = 'JazzHR POST error';

const SLEEP_AFTER_TRANSFER = 2000;

const STARTUP_JOBS_GET_APPLICATIONS_CONCURRENCY = 20;
const JAZZ_HR_GET_APPLICANTS_CONCURRENCY = 30;
const TRANSFER_APPLICATIONS_CONCURRENCY = 10;

const ERROR_TYPES = {
  CREATE_APPLICANT: 'CREATE_APPLICANT',
  CREATE_NOTE: 'CREATE_NOTE',
};
module.exports = {
  STARTUP_JOBS_ID_PREFIX,
  JAZZ_HR_POST_ERROR,
  SLEEP_AFTER_TRANSFER,
  STARTUP_JOBS_GET_APPLICATIONS_CONCURRENCY,
  JAZZ_HR_GET_APPLICANTS_CONCURRENCY,
  TRANSFER_APPLICATIONS_CONCURRENCY,
  ERROR_TYPES,
};
